name: network_file_cache_http
description: HTTP adapter for network_file_cache.
version: 0.0.2
repository: https://github.com/valeriinov/network_file_cache
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  network_file_cache:
    git:
      url: https://github.com/valeriinov/network_file_cache
      ref: 0.0.2
      path: packages/network_file_cache

dev_dependencies:
  flutter_test:
    sdk: flutter
