name: network_cached_image
description: ImageProvider built on network_file_cache.
version: 0.1.0
repository: https://github.com/valeriinov/network_file_cache
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  network_file_cache:
    git:
      url: https://github.com/valeriinov/network_file_cache
      ref: 0.1.0
      path: packages/network_file_cache

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
